name: chaqchuq
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  shared_preferences: ^2.5.2
  flutter_screenutil: ^5.9.3
  easy_localization: ^3.0.7+1
  intl: ^0.19.0
  dots_indicator: ^3.0.0
  fluttertoast: ^8.2.10
  carousel_slider: ^5.0.0
  animated_snack_bar: ^0.4.0
  rive: ^0.13.20
  flutter_native_splash: ^2.4.5
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/products/
    - assets/riv/
    - assets/languages/en-US.json
    - assets/languages/uz-UZ.json
    - assets/languages/ru-RU.json

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
    - family: Titan
      fonts:
        - asset: assets/fonts/TitanOne-Regular.ttf

  
